"""Add common query indexes

Revision ID: 1b649d4f76f6
Revises: 5cd61a16b3f9
Create Date: 2026-06-03 00:12:20.372172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b649d4f76f6'
down_revision = '5cd61a16b3f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badges_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_badges_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_badges_name'), ['name'], unique=False)

    with op.batch_alter_table('group_goal_contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_goal_contributions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_goal_contributions_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_goal_contributions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_goal_contributions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('group_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_goals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_goals_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_goals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_goals_title'), ['title'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transactions_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transactions_related_reward_purchase_id'), ['related_reward_purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transactions_related_task_completion_id'), ['related_task_completion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('reward_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_categories_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_categories_name'), ['name'], unique=True)

    with op.batch_alter_table('reward_purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_purchases_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_purchases_reviewed_at'), ['reviewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_purchases_reviewed_by_id'), ['reviewed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_purchases_reward_id'), ['reward_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_purchases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_purchases_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rewards_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_rewards_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rewards_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_rewards_name'), ['name'], unique=False)

    with op.batch_alter_table('task_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_categories_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_categories_name'), ['name'], unique=True)

    with op.batch_alter_table('task_completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_completions_reviewed_at'), ['reviewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_completions_reviewed_by_id'), ['reviewed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_completions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_completions_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_completions_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_completions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_is_hot'), ['is_hot'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_title'), ['title'], unique=False)

    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_badges_badge_id'), ['badge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_badges_earned_at'), ['earned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_badges_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active_account'), ['is_active_account'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('wishlist_contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_contributions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_contributions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_contributions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_contributions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_items_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_items_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_items_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_items_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('wishlist_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_requests_requested_name'), ['requested_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_requests_reviewed_at'), ['reviewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_requests_reviewed_by_id'), ['reviewed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_requests_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_requests_status'))
        batch_op.drop_index(batch_op.f('ix_wishlist_requests_reviewed_by_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_requests_reviewed_at'))
        batch_op.drop_index(batch_op.f('ix_wishlist_requests_requested_name'))
        batch_op.drop_index(batch_op.f('ix_wishlist_requests_created_at'))

    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_items_status'))
        batch_op.drop_index(batch_op.f('ix_wishlist_items_name'))
        batch_op.drop_index(batch_op.f('ix_wishlist_items_is_active'))
        batch_op.drop_index(batch_op.f('ix_wishlist_items_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_items_created_at'))

    with op.batch_alter_table('wishlist_contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_contributions_user_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_contributions_status'))
        batch_op.drop_index(batch_op.f('ix_wishlist_contributions_item_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_contributions_created_at'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_active_account'))
        batch_op.drop_index(batch_op.f('ix_users_display_name'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badges_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_badges_earned_at'))
        batch_op.drop_index(batch_op.f('ix_user_badges_badge_id'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_title'))
        batch_op.drop_index(batch_op.f('ix_tasks_is_hot'))
        batch_op.drop_index(batch_op.f('ix_tasks_is_active'))
        batch_op.drop_index(batch_op.f('ix_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_category'))

    with op.batch_alter_table('task_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_completions_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_completions_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_completions_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_task_completions_status'))
        batch_op.drop_index(batch_op.f('ix_task_completions_reviewed_by_id'))
        batch_op.drop_index(batch_op.f('ix_task_completions_reviewed_at'))

    with op.batch_alter_table('task_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_categories_name'))
        batch_op.drop_index(batch_op.f('ix_task_categories_is_active'))
        batch_op.drop_index(batch_op.f('ix_task_categories_created_at'))

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rewards_name'))
        batch_op.drop_index(batch_op.f('ix_rewards_is_active'))
        batch_op.drop_index(batch_op.f('ix_rewards_created_at'))
        batch_op.drop_index(batch_op.f('ix_rewards_category'))

    with op.batch_alter_table('reward_purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_purchases_user_id'))
        batch_op.drop_index(batch_op.f('ix_reward_purchases_status'))
        batch_op.drop_index(batch_op.f('ix_reward_purchases_reward_id'))
        batch_op.drop_index(batch_op.f('ix_reward_purchases_reviewed_by_id'))
        batch_op.drop_index(batch_op.f('ix_reward_purchases_reviewed_at'))
        batch_op.drop_index(batch_op.f('ix_reward_purchases_requested_at'))

    with op.batch_alter_table('reward_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_categories_name'))
        batch_op.drop_index(batch_op.f('ix_reward_categories_is_active'))
        batch_op.drop_index(batch_op.f('ix_reward_categories_created_at'))

    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_point_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_point_transactions_related_task_completion_id'))
        batch_op.drop_index(batch_op.f('ix_point_transactions_related_reward_purchase_id'))
        batch_op.drop_index(batch_op.f('ix_point_transactions_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_point_transactions_created_at'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    with op.batch_alter_table('group_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_goals_title'))
        batch_op.drop_index(batch_op.f('ix_group_goals_status'))
        batch_op.drop_index(batch_op.f('ix_group_goals_is_active'))
        batch_op.drop_index(batch_op.f('ix_group_goals_created_at'))

    with op.batch_alter_table('group_goal_contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_goal_contributions_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_goal_contributions_status'))
        batch_op.drop_index(batch_op.f('ix_group_goal_contributions_goal_id'))
        batch_op.drop_index(batch_op.f('ix_group_goal_contributions_created_at'))

    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badges_name'))
        batch_op.drop_index(batch_op.f('ix_badges_created_at'))
        batch_op.drop_index(batch_op.f('ix_badges_code'))

    # ### end Alembic commands ###
